### ISSUE TITLE
[아이템 1] 정적 팩토리 메소드 도입으로 얻게 되는 유연성

### ISSUE THREAD

**Issue by 05AM** [Java-SWU/effective-java#11]
> p.10 API를 만들 때 이 유연성을 응용하면 구현 클래스를 공개하지 않고도 그 객체를 반환할 수 있어 API를 작게 유지할 수 있다.

**Comment by decten** [comment]
> https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/
```
Car carDto = CarDto.from(car); // 정적 팩토리 메서드를 쓴 경우
CarDto carDto = new CarDto(car.getName(), car.getPosition); // 생성자를 쓴 경우
```
은닉 효과를 가질 수 있어 구현 클래스를 드러내지 않고 API가 작게 유지된다고 합니다
